---
title: "Réponses aux questions du rapport précédent"
author: "SAMA Fousseni"
date: "`r Sys.Date()`"
output: word_document
---
  
```{r message=FALSE, warning=FALSE}
library("devtools")
## Warning: le package 'devtools' a été compilé avec la version R 4.1.3
## Le chargement a nécessité le package : usethis
## Warning: le package 'usethis' a été compilé avec la version R 4.1.3
# Install "HiCImpute" package from github.
# install_github("https://github.com/sl-lin/HiCImpute")
library("HiCImpute")

library("tidyverse")
library("FactoMineR")
library("factoextra")
library("ggpubr")
```


# Comparaison des matrices issues de la simulation et du code R

```{r message=FALSE, warning=FALSE}

load("rdata/mat_inci_beetween_bacs.rda")

mat <- as.matrix(
    read.table(
      paste0("rdata/single_cell_hic_data/hic_mat_", sprintf("%03d", 1), ".txt"), 
      quote="\"", 
      comment.char="", 
      stringsAsFactors = FALSE
    ) 
  )

```



# Construction de clusters avec les matrices scHic simulées (contacts entre bacs de 4billes)

```{r message=FALSE, warning=FALSE}
# Disposition des données dans une liste
ncol = 562
ncells = 250
data_dim = ncol*(ncol-1)/2

hicImpute_data <- matrix(
  0, 
  nrow = data_dim, 
  ncol = ncells, 
  byrow = TRUE
)

for (i in seq_len(ncells)) {
  mat <- as.matrix(
    read.table(
      paste0("rdata/single_cell_hic_data/hic_mat_", sprintf("%03d", i), ".txt"), 
      quote="\"", 
      comment.char="", 
      stringsAsFactors = FALSE
    ) 
  )
  
  hicImpute_data[, i] <- mat[upper.tri(mat)]
}
rm("mat")
#colnames(hicImpute_data) <- str_c("cell", sprintf("%03d", seq(ncells)))
```

```{r message=FALSE, warning=FALSE}
# Nous prenons ici les paramètres par défaut de la fonction MCMCImpute. Cepandant comme nous ne disposons pas de données en vrac, nous mettons bulk à NULL. Nous pouvons cependant aussi générer les données en vrac à partir du code du simulation de départ en prennant en compte toutes les cellules comme le faisait les auteurs.
set.seed(1234)

MCMCImpute_result=MCMCImpute(
  scHiC=hicImpute_data,
  bulk=apply(hicImpute_data,1,sum), 
  expected=NULL,
  startval=c(100,100,10,8,10,0.1,900,0.2,0,replicate(dim(hicImpute_data)[2],8)),
  n=562,
  mc.cores = 2,
  cutoff=0.5, 
  niter=200,
  burnin=100
)
```


# Comparaison des résulats de clustering : Similarité (clusters_similarity.R)

```{r}
cluster_data <- as_tibble(
  data.frame(
    hicImput_clus = cluster$cluster,
    hicImput_cells = names(cluster$cluster),
    hcpc_clus = hcpc_cluster$data.clust$clust,
    hcpc_cells = row.names(hcpc_cluster$data.clust)
  )
)


hicImput_cluster_unique = unique(cluster_data$hicImput_clus)
hcpc_cluster_unique = unique(cluster_data$hcpc_clus)

similarity_results = matrix(
  NA,
  nrow = length(hicImput_cluster_unique), 
  ncol = 5,
  dimnames = list(
    paste0("cluster ",1:length(hicImput_cluster_unique)), 
    c("hcpc_cluster", "hcpc_cluster_length", "hicImput_cluster", "hicImput_cluster_length", "similarite")
  )

)

for (i in seq(length(hcpc_cluster_unique))) {
  
  k = hcpc_cluster_unique[i]
  cellsi = cluster_data[cluster_data$hcpc_clus==k, ]$hcpc_cells
  perc = 0
  for (j in hicImput_cluster_unique) {
    
    cellsj = cluster_data[cluster_data$hicImput_clus==j, ]$hicImput_cells
    perc = length(intersect(cellsi, cellsj))/max(length(cellsi), length(cellsj))
    
    if(perc>0){
      cluster_to_keep = c(j, length(cellsj), perc)
    }
  }
  
  similarity_results[i, 1] <- k
  similarity_results[i, 2] <- length(cellsi)
  similarity_results[i, 3] <- cluster_to_keep[1]
  similarity_results[i, 4] <- cluster_to_keep[2]
  similarity_results[i, 5] <- cluster_to_keep[3]
  
  hicImput_cluster = hicImput_cluster[hicImput_cluster != cluster_to_keep[1]]
}

similarity_results[similarity_results[, 5]==1, ]
```


