---
title: "Rapport de la semaine du 07 Novembre 2022"
author: "SAMA Fousseni"
date: "2022-11-07"
output: word_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(data.table)
library(vroom)
```


# Pour la cellule ENDO :

```{r message=FALSE, warning=FALSE}
# To charge large dataset
endo_cell_data <- fread("rdata/SCORE_ABC_RESULTS/ENDO_CELL/EnhancerPredictionsAllPutative.txt")

# Création du vecteur des seuils
seuils <- seq(0, 0.10, 0.001)

# Création de la matrice de données qui contiendra le résumé des statistiques descriptives
contact_G_H_dist <- matrix(
  NA, 
  nrow = length(seuils), 
  ncol = 9,
  dimnames = list(
    c(),
    c("threshold", "Reject", "Keep", "min_TarGene", "frst_Quar_TarGene", "median_TarGene", "mean_TarGene", "third_Quar_TarGene", "max_TarGene"))
)

# Boucle sur les valeurs du seuils et production des statistiques descriptives
## contact_G_H_dist Contient non seulement les statistiques descriptives mais aussi le nombre de nombre de paires Gene-Enhancer retenues et rejetées
for (i in seq_len(length(seuils))) {
  contact_G_H_dist[i, 1] <- seuils[i]
  contact_G_H_dist[i, 2] <- table(endo_cell_data$ABC.Score>seuils[i])[1]
  contact_G_H_dist[i, 3] <- table(endo_cell_data$ABC.Score>seuils[i])[2]
  
  summarise <- data.frame(
    table(endo_cell_data%>%filter(ABC.Score>seuils[i])%>%select(TargetGene))
  )%>%
    summarise(
      min_TarGene = min(Freq, na.rm = TRUE),
      frst_Quar_TarGene = quantile(Freq, 0.25, na.rm = FALSE),
      median_TarGene = quantile(Freq, 0.5, na.rm = FALSE),
      mean_TarGene = mean(Freq, na.rm = TRUE),
      third_Quar_TarGene = quantile(Freq, 0.75, na.rm = FALSE),
      max_TarGene = max(Freq, na.rm = TRUE)
    )
  
  contact_G_H_dist[i, 4] <- summarise$min_TarGene
  contact_G_H_dist[i, 5] <- summarise$frst_Quar_TarGene
  contact_G_H_dist[i, 6] <- summarise$median_TarGene
  contact_G_H_dist[i, 7] <- summarise$mean_TarGene
  contact_G_H_dist[i, 8] <- summarise$third_Quar_TarGene
  contact_G_H_dist[i, 9] <- summarise$max_TarGene
}

hist(contact_G_H_dist[, 2])

# Visualiser les données sur les genes retenus et rejetés
contact_G_H_dist <- data.frame(contact_G_H_dist)
ggplot(contact_G_H_dist) + geom_col(aes(x = threshold, y = Reject))+ ggtitle("Nombre de paires gènes Enhancers rejeté en fonction des seuils pour \n la cellule ENDO")+ labs(y = "Nombre de paires", x = "Seuils (threshold)")
ggplot(contact_G_H_dist) + geom_col(aes(x = threshold, y = Keep))+ ggtitle("Nombre de paires gènes Enhancers retenu en fonction des seuils pour \n la cellule ENDO")+ labs(y = "Nombre de paires", x = "Seuils (threshold)")
ggplot(contact_G_H_dist) + geom_col(aes(x = threshold, y = mean_TarGene))+ ggtitle("Nombre moyen de paires gènes Enhancers retenu en fonction des seuils pour \n la cellule ENDO")+ labs(y = "Nombre de paires", x = "Seuils (threshold)")
rm("endo_cell_data")
```


# Pour la cellule L4 :


```{r message=FALSE, warning=FALSE}
# To charge large dataset
L4_cell_data <- fread("rdata/SCORE_ABC_RESULTS/L4/EnhancerPredictionsAllPutative.txt")

# Création du vecteur des seuils
seuils <- seq(0, 0.10, 0.001)

# Création de la matrice de données qui contiendra le résumé des statistiques descriptives
contact_G_H_dist <- matrix(
  NA, 
  nrow = length(seuils), 
  ncol = 9,
  dimnames = list(
    c(),
    c("threshold", "Reject", "Keep", "min_TarGene", "frst_Quar_TarGene", "median_TarGene", "mean_TarGene", "third_Quar_TarGene", "max_TarGene"))
)

# Boucle sur les valeurs du seuils et production des statistiques descriptives
## contact_G_H_dist Contient non seulement les statistiques descriptives mais aussi le nombre de nombre de paires Gene-Enhancer retenues et rejetées
for (i in seq_len(length(seuils))) {
  contact_G_H_dist[i, 1] <- seuils[i]
  contact_G_H_dist[i, 2] <- table(L4_cell_data$ABC.Score>seuils[i])[1]
  contact_G_H_dist[i, 3] <- table(L4_cell_data$ABC.Score>seuils[i])[2]
  
  summarise <- data.frame(
    table(L4_cell_data%>%filter(ABC.Score>seuils[i])%>%select(TargetGene))
  )%>%
    summarise(
      min_TarGene = min(Freq, na.rm = TRUE),
      frst_Quar_TarGene = quantile(Freq, 0.25, na.rm = FALSE),
      median_TarGene = quantile(Freq, 0.5, na.rm = FALSE),
      mean_TarGene = mean(Freq, na.rm = TRUE),
      third_Quar_TarGene = quantile(Freq, 0.75, na.rm = FALSE),
      max_TarGene = max(Freq, na.rm = TRUE)
    )
  
  contact_G_H_dist[i, 4] <- summarise$min_TarGene
  contact_G_H_dist[i, 5] <- summarise$frst_Quar_TarGene
  contact_G_H_dist[i, 6] <- summarise$median_TarGene
  contact_G_H_dist[i, 7] <- summarise$mean_TarGene
  contact_G_H_dist[i, 8] <- summarise$third_Quar_TarGene
  contact_G_H_dist[i, 9] <- summarise$max_TarGene
}

hist(contact_G_H_dist[, 2])

# Visualiser les données sur les genes retenus et rejetés
contact_G_H_dist <- data.frame(contact_G_H_dist)
ggplot(contact_G_H_dist) + geom_col(aes(x = threshold, y = Reject))+ ggtitle("Nombre de paires gènes Enhancers rejeté en fonction des seuils pour \n la cellule L4")+ labs(y = "Nombre de paires", x = "Seuils (threshold)")
ggplot(contact_G_H_dist) + geom_col(aes(x = threshold, y = Keep))+ ggtitle("Nombre de paires gènes Enhancers retenu en fonction des seuils pour \n la cellule L4")+ labs(y = "Nombre de paires", x = "Seuils (threshold)")
ggplot(contact_G_H_dist) + geom_col(aes(x = threshold, y = mean_TarGene))+ ggtitle("Nombre moyen de paires gènes Enhancers retenu en fonction des seuils pour \n la cellule L4")+ labs(y = "Nombre de paires", x = "Seuils (threshold)")
rm("L4_cell_data")
```


# Pour la cellule L5 :


```{r message=FALSE, warning=FALSE}
# To charge large dataset
L5_cell_data <- fread("rdata/SCORE_ABC_RESULTS/L5/EnhancerPredictionsAllPutative.txt")

# Création du vecteur des seuils
seuils <- seq(0, 0.10, 0.001)

# Création de la matrice de données qui contiendra le résumé des statistiques descriptives
contact_G_H_dist <- matrix(
  NA, 
  nrow = length(seuils), 
  ncol = 9,
  dimnames = list(
    c(),
    c("threshold", "Reject", "Keep", "min_TarGene", "frst_Quar_TarGene", "median_TarGene", "mean_TarGene", "third_Quar_TarGene", "max_TarGene"))
)

# Boucle sur les valeurs du seuils et production des statistiques descriptives
## contact_G_H_dist Contient non seulement les statistiques descriptives mais aussi le nombre de nombre de paires Gene-Enhancer retenues et rejetées
for (i in seq_len(length(seuils))) {
  contact_G_H_dist[i, 1] <- seuils[i]
  contact_G_H_dist[i, 2] <- table(L5_cell_data$ABC.Score>seuils[i])[1]
  contact_G_H_dist[i, 3] <- table(L5_cell_data$ABC.Score>seuils[i])[2]
  
  summarise <- data.frame(
    table(L5_cell_data%>%filter(ABC.Score>seuils[i])%>%select(TargetGene))
  )%>%
    summarise(
      min_TarGene = min(Freq, na.rm = TRUE),
      frst_Quar_TarGene = quantile(Freq, 0.25, na.rm = FALSE),
      median_TarGene = quantile(Freq, 0.5, na.rm = FALSE),
      mean_TarGene = mean(Freq, na.rm = TRUE),
      third_Quar_TarGene = quantile(Freq, 0.75, na.rm = FALSE),
      max_TarGene = max(Freq, na.rm = TRUE)
    )
  
  contact_G_H_dist[i, 4] <- summarise$min_TarGene
  contact_G_H_dist[i, 5] <- summarise$frst_Quar_TarGene
  contact_G_H_dist[i, 6] <- summarise$median_TarGene
  contact_G_H_dist[i, 7] <- summarise$mean_TarGene
  contact_G_H_dist[i, 8] <- summarise$third_Quar_TarGene
  contact_G_H_dist[i, 9] <- summarise$max_TarGene
}

hist(contact_G_H_dist[, 2])

# Visualiser les données sur les genes retenus et rejetés
contact_G_H_dist <- data.frame(contact_G_H_dist)
ggplot(contact_G_H_dist) + geom_col(aes(x = threshold, y = Reject))+ ggtitle("Nombre de paires gènes Enhancers rejeté en fonction des seuils pour \n la cellule L5")+ labs(y = "Nombre de paires", x = "Seuils (threshold)")
ggplot(contact_G_H_dist) + geom_col(aes(x = threshold, y = Keep))+ ggtitle("Nombre de paires gènes Enhancers retenu en fonction des seuils pour \n la cellule L5")+ labs(y = "Nombre de paires", x = "Seuils (threshold)")
ggplot(contact_G_H_dist) + geom_col(aes(x = threshold, y = mean_TarGene))+ ggtitle("Nombre moyen de paires gènes Enhancers retenu en fonction des seuils pour \n la cellule L5")+ labs(y = "Nombre de paires", x = "Seuils (threshold)")
rm("L5_cell_data")
```


# Pour la cellule L6 :


```{r message=FALSE, warning=FALSE}
# To charge large dataset
L6_cell_data <- fread("rdata/SCORE_ABC_RESULTS/L6/EnhancerPredictionsAllPutative.txt")

# Création du vecteur des seuils
seuils <- seq(0, 0.10, 0.001)

# Création de la matrice de données qui contiendra le résumé des statistiques descriptives
contact_G_H_dist <- matrix(
  NA, 
  nrow = length(seuils), 
  ncol = 9,
  dimnames = list(
    c(),
    c("threshold", "Reject", "Keep", "min_TarGene", "frst_Quar_TarGene", "median_TarGene", "mean_TarGene", "third_Quar_TarGene", "max_TarGene"))
)

# Boucle sur les valeurs du seuils et production des statistiques descriptives
## contact_G_H_dist Contient non seulement les statistiques descriptives mais aussi le nombre de nombre de paires Gene-Enhancer retenues et rejetées
for (i in seq_len(length(seuils))) {
  contact_G_H_dist[i, 1] <- seuils[i]
  contact_G_H_dist[i, 2] <- table(L6_cell_data$ABC.Score>seuils[i])[1]
  contact_G_H_dist[i, 3] <- table(L6_cell_data$ABC.Score>seuils[i])[2]
  
  summarise <- data.frame(
    table(L6_cell_data%>%filter(ABC.Score>seuils[i])%>%select(TargetGene))
  )%>%
    summarise(
      min_TarGene = min(Freq, na.rm = TRUE),
      frst_Quar_TarGene = quantile(Freq, 0.25, na.rm = FALSE),
      median_TarGene = quantile(Freq, 0.5, na.rm = FALSE),
      mean_TarGene = mean(Freq, na.rm = TRUE),
      third_Quar_TarGene = quantile(Freq, 0.75, na.rm = FALSE),
      max_TarGene = max(Freq, na.rm = TRUE)
    )
  
  contact_G_H_dist[i, 4] <- summarise$min_TarGene
  contact_G_H_dist[i, 5] <- summarise$frst_Quar_TarGene
  contact_G_H_dist[i, 6] <- summarise$median_TarGene
  contact_G_H_dist[i, 7] <- summarise$mean_TarGene
  contact_G_H_dist[i, 8] <- summarise$third_Quar_TarGene
  contact_G_H_dist[i, 9] <- summarise$max_TarGene
}

hist(contact_G_H_dist[, 2])

# Visualiser les données sur les genes retenus et rejetés
contact_G_H_dist <- data.frame(contact_G_H_dist)
ggplot(contact_G_H_dist) + geom_col(aes(x = threshold, y = Reject))+ ggtitle("Nombre de paires gènes Enhancers rejeté en fonction des seuils pour \n la cellule L6")+ labs(y = "Nombre de paires", x = "Seuils (threshold)")
ggplot(contact_G_H_dist) + geom_col(aes(x = threshold, y = Keep))+ ggtitle("Nombre de paires gènes Enhancers retenu en fonction des seuils pour \n la cellule L6")+ labs(y = "Nombre de paires", x = "Seuils (threshold)")
ggplot(contact_G_H_dist) + geom_col(aes(x = threshold, y = mean_TarGene))+ ggtitle("Nombre moyen de paires gènes Enhancers retenu en fonction des seuils pour \n la cellule L6")+ labs(y = "Nombre de paires", x = "Seuils (threshold)")
rm("L6_cell_data")
```

# Pour la cellule MG :


```{r message=FALSE, warning=FALSE}
# To charge large dataset
MG_cell_data <- fread("rdata/SCORE_ABC_RESULTS/MG/EnhancerPredictionsAllPutative.txt")

# Création du vecteur des seuils
seuils <- seq(0, 0.10, 0.001)

# Création de la matrice de données qui contiendra le résumé des statistiques descriptives
contact_G_H_dist <- matrix(
  NA, 
  nrow = length(seuils), 
  ncol = 9,
  dimnames = list(
    c(),
    c("threshold", "Reject", "Keep", "min_TarGene", "frst_Quar_TarGene", "median_TarGene", "mean_TarGene", "third_Quar_TarGene", "max_TarGene"))
)

# Boucle sur les valeurs du seuils et production des statistiques descriptives
## contact_G_H_dist Contient non seulement les statistiques descriptives mais aussi le nombre de nombre de paires Gene-Enhancer retenues et rejetées
for (i in seq_len(length(seuils))) {
  contact_G_H_dist[i, 1] <- seuils[i]
  contact_G_H_dist[i, 2] <- table(MG_cell_data$ABC.Score>seuils[i])[1]
  contact_G_H_dist[i, 3] <- table(MG_cell_data$ABC.Score>seuils[i])[2]
  
  summarise <- data.frame(
    table(MG_cell_data%>%filter(ABC.Score>seuils[i])%>%select(TargetGene))
  )%>%
    summarise(
      min_TarGene = min(Freq, na.rm = TRUE),
      frst_Quar_TarGene = quantile(Freq, 0.25, na.rm = FALSE),
      median_TarGene = quantile(Freq, 0.5, na.rm = FALSE),
      mean_TarGene = mean(Freq, na.rm = TRUE),
      third_Quar_TarGene = quantile(Freq, 0.75, na.rm = FALSE),
      max_TarGene = max(Freq, na.rm = TRUE)
    )
  
  contact_G_H_dist[i, 4] <- summarise$min_TarGene
  contact_G_H_dist[i, 5] <- summarise$frst_Quar_TarGene
  contact_G_H_dist[i, 6] <- summarise$median_TarGene
  contact_G_H_dist[i, 7] <- summarise$mean_TarGene
  contact_G_H_dist[i, 8] <- summarise$third_Quar_TarGene
  contact_G_H_dist[i, 9] <- summarise$max_TarGene
}

hist(contact_G_H_dist[, 2])

# Visualiser les données sur les genes retenus et rejetés
contact_G_H_dist <- data.frame(contact_G_H_dist)
ggplot(contact_G_H_dist) + geom_col(aes(x = threshold, y = Reject))+ ggtitle("Nombre de paires gènes Enhancers rejeté en fonction des seuils pour \n la cellule MG")+ labs(y = "Nombre de paires", x = "Seuils (threshold)")
ggplot(contact_G_H_dist) + geom_col(aes(x = threshold, y = Keep))+ ggtitle("Nombre de paires gènes Enhancers retenu en fonction des seuils pour \n la cellule MG")+ labs(y = "Nombre de paires", x = "Seuils (threshold)")
ggplot(contact_G_H_dist) + geom_col(aes(x = threshold, y = mean_TarGene))+ ggtitle("Nombre moyen de paires gènes Enhancers retenu en fonction des seuils pour \n la cellule MG")+ labs(y = "Nombre de paires", x = "Seuils (threshold)")
rm("MG_cell_data")
```


# Pour la cellule MP :


```{r message=FALSE, warning=FALSE}
# To charge large dataset
MP_cell_data <- fread("rdata/SCORE_ABC_RESULTS/MP/EnhancerPredictionsAllPutative.txt")

# Création du vecteur des seuils
seuils <- seq(0, 0.10, 0.001)

# Création de la matrice de données qui contiendra le résumé des statistiques descriptives
contact_G_H_dist <- matrix(
  NA, 
  nrow = length(seuils), 
  ncol = 9,
  dimnames = list(
    c(),
    c("threshold", "Reject", "Keep", "min_TarGene", "frst_Quar_TarGene", "median_TarGene", "mean_TarGene", "third_Quar_TarGene", "max_TarGene"))
)

# Boucle sur les valeurs du seuils et production des statistiques descriptives
## contact_G_H_dist Contient non seulement les statistiques descriptives mais aussi le nombre de nombre de paires Gene-Enhancer retenues et rejetées
for (i in seq_len(length(seuils))) {
  contact_G_H_dist[i, 1] <- seuils[i]
  contact_G_H_dist[i, 2] <- table(MP_cell_data$ABC.Score>seuils[i])[1]
  contact_G_H_dist[i, 3] <- table(MP_cell_data$ABC.Score>seuils[i])[2]
  
  summarise <- data.frame(
    table(MP_cell_data%>%filter(ABC.Score>seuils[i])%>%select(TargetGene))
  )%>%
    summarise(
      min_TarGene = min(Freq, na.rm = TRUE),
      frst_Quar_TarGene = quantile(Freq, 0.25, na.rm = FALSE),
      median_TarGene = quantile(Freq, 0.5, na.rm = FALSE),
      mean_TarGene = mean(Freq, na.rm = TRUE),
      third_Quar_TarGene = quantile(Freq, 0.75, na.rm = FALSE),
      max_TarGene = max(Freq, na.rm = TRUE)
    )
  
  contact_G_H_dist[i, 4] <- summarise$min_TarGene
  contact_G_H_dist[i, 5] <- summarise$frst_Quar_TarGene
  contact_G_H_dist[i, 6] <- summarise$median_TarGene
  contact_G_H_dist[i, 7] <- summarise$mean_TarGene
  contact_G_H_dist[i, 8] <- summarise$third_Quar_TarGene
  contact_G_H_dist[i, 9] <- summarise$max_TarGene
}

hist(contact_G_H_dist[, 2])

# Visualiser les données sur les genes retenus et rejetés
contact_G_H_dist <- data.frame(contact_G_H_dist)
ggplot(contact_G_H_dist) + geom_col(aes(x = threshold, y = Reject))+ ggtitle("Nombre de paires gènes Enhancers rejeté en fonction des seuils pour \n la cellule MP")+ labs(y = "Nombre de paires", x = "Seuils (threshold)")
ggplot(contact_G_H_dist) + geom_col(aes(x = threshold, y = Keep))+ ggtitle("Nombre de paires gènes Enhancers retenu en fonction des seuils pour \n la cellule MP")+ labs(y = "Nombre de paires", x = "Seuils (threshold)")
ggplot(contact_G_H_dist) + geom_col(aes(x = threshold, y = mean_TarGene))+ ggtitle("Nombre moyen de paires gènes Enhancers retenu en fonction des seuils pour \n la cellule MP")+ labs(y = "Nombre de paires", x = "Seuils (threshold)")
rm("MP_cell_data")
```


# Pour la cellule Ndnf :

```{r message=FALSE, warning=FALSE}
# To charge large dataset
Ndnf_cell_data <- fread("rdata/SCORE_ABC_RESULTS/Ndnf/EnhancerPredictionsAllPutative.txt")

# Création du vecteur des seuils
seuils <- seq(0, 0.10, 0.001)

# Création de la matrice de données qui contiendra le résumé des statistiques descriptives
contact_G_H_dist <- matrix(
  NA, 
  nrow = length(seuils), 
  ncol = 9,
  dimnames = list(
    c(),
    c("threshold", "Reject", "Keep", "min_TarGene", "frst_Quar_TarGene", "median_TarGene", "mean_TarGene", "third_Quar_TarGene", "max_TarGene"))
)

# Boucle sur les valeurs du seuils et production des statistiques descriptives
## contact_G_H_dist Contient non seulement les statistiques descriptives mais aussi le nombre de nombre de paires Gene-Enhancer retenues et rejetées
for (i in seq_len(length(seuils))) {
  contact_G_H_dist[i, 1] <- seuils[i]
  contact_G_H_dist[i, 2] <- table(Ndnf_cell_data$ABC.Score>seuils[i])[1]
  contact_G_H_dist[i, 3] <- table(Ndnf_cell_data$ABC.Score>seuils[i])[2]
  
  summarise <- data.frame(
    table(Ndnf_cell_data%>%filter(ABC.Score>seuils[i])%>%select(TargetGene))
  )%>%
    summarise(
      min_TarGene = min(Freq, na.rm = TRUE),
      frst_Quar_TarGene = quantile(Freq, 0.25, na.rm = FALSE),
      median_TarGene = quantile(Freq, 0.5, na.rm = FALSE),
      mean_TarGene = mean(Freq, na.rm = TRUE),
      third_Quar_TarGene = quantile(Freq, 0.75, na.rm = FALSE),
      max_TarGene = max(Freq, na.rm = TRUE)
    )
  
  contact_G_H_dist[i, 4] <- summarise$min_TarGene
  contact_G_H_dist[i, 5] <- summarise$frst_Quar_TarGene
  contact_G_H_dist[i, 6] <- summarise$median_TarGene
  contact_G_H_dist[i, 7] <- summarise$mean_TarGene
  contact_G_H_dist[i, 8] <- summarise$third_Quar_TarGene
  contact_G_H_dist[i, 9] <- summarise$max_TarGene
}

hist(contact_G_H_dist[, 2])

# Visualiser les données sur les genes retenus et rejetés
contact_G_H_dist <- data.frame(contact_G_H_dist)
ggplot(contact_G_H_dist) + geom_col(aes(x = threshold, y = Reject))+ ggtitle("Nombre de paires gènes Enhancers rejeté en fonction des seuils pour \n la cellule Ndnf")+ labs(y = "Nombre de paires", x = "Seuils (threshold)")
ggplot(contact_G_H_dist) + geom_col(aes(x = threshold, y = Keep))+ ggtitle("Nombre de paires gènes Enhancers retenu en fonction des seuils pour \n la cellule Ndnf")+ labs(y = "Nombre de paires", x = "Seuils (threshold)")
ggplot(contact_G_H_dist) + geom_col(aes(x = threshold, y = mean_TarGene))+ ggtitle("Nombre moyen de paires gènes Enhancers retenu en fonction des seuils pour \n la cellule Ndnf")+ labs(y = "Nombre de paires", x = "Seuils (threshold)")
rm("Ndnf_cell_data")
```

Nombre_moyen_GeneEnhancers_retenu_.png
GenesEnhancers_retenu_.png
GenesEnhancers_rejete_.png




