---
title: "RAPPORT"
author: "SAMA Fousseni"
date: "22/05/2022"
output: word_document
---


```{r setup, message=FALSE, warning=FALSE}
# Chargement des librairies
library(rmarkdown)
library(rgl)
library(magick)
library(randomcoloR)
library(readr)
library(tidyverse)
library(igraph)
library(ggpubr)
library(RColorBrewer)
library(finalfit)
library(knitr)
library(plotly)
knitr::knit_hooks$set(webgl = hook_webgl)
#rm(list=ls())
```

```{r message=FALSE, warning=FALSE}
# Les fonctions utilitaires
## Simple fonction de distance
dist_func <- function(point_1, point_2, dist_method="eucludien"){
  if(dist_method=="eucludien"){
    D = sqrt(apply((point_1 - point_2)^2, MARGIN = 1, FUN = sum))
  }
}

## Apply mean distance 1:m
m_dist_func <- function(data_frame1, data_frame2, type = "diff_mean", output = "matrix", rep1 = 1, rep2 = 2){
  n1 = nrow(data_frame1)
  n2 = nrow(data_frame2)
  
  if(output == "matrix"){
    mat.distance.diff = matrix(NA, nrow = n1, ncol = n2)
    if(type == "diff_mean"){
      row_names1 <- paste0("R", rep1, sprintf("%02d", seq_len(n1)))
      row_names2 <- paste0("R", rep2, sprintf("%02d", seq_len(n2)))
    }else if(type == "diff_ind"){
      row_names1 <- paste0("R", rep1, "B", sprintf("%02d", data_frame1[, 4]), "CRH", sprintf("%02d", data_frame1[, 6]))
      row_names2 <- paste0("R", rep2, "B", sprintf("%02d", data_frame2[, 4]), "CRH", sprintf("%02d", data_frame2[, 6]))
    }
    
    rownames(mat.distance.diff) <- row_names1
    colnames(mat.distance.diff) <- row_names2
    
  }else if(output == "data.frame"){
    mat.distance.diff = matrix(NA, nrow = n1*n2, ncol = 2)
  }
  
  if(output == "matrix"){
    for (i in seq_len(n1)) {
      for (j in seq_len(n2)) {
        mat.distance.diff[i, j] = round(dist_func(data_frame1[i, 1:3], data_frame2[j, 1:3]), 2)
      }
    }
  }else if(output == "data.frame"){
    #### Calcul des différences de distances moyenne par CRH ####
    if(type == "diff_mean"){
      for (i in 1:n1) {
        for (j in 1:n2) {
          mat.distance.diff[n2*i-n2+j, 1] = paste0("R", rep1, sprintf("%02d", i),"-","R", rep2, sprintf("%02d", j))
          mat.distance.diff[n2*i-n2+j, 2] = round(dist_func(data_frame1[i, 1:3], data_frame2[j, 1:3]), 2)
        }
      }
      #### Calcul des différences de distances par bille ####
    }else if(type == "diff_ind"){
      for (i in 1:n1) {
        for (j in 1:n2) {
          mat.distance.diff[n2*i-n2+j, 1] <- paste0(
            "R", rep1, "B", sprintf("%02d", data_frame1[i, 4]), "CRH", sprintf("%02d", data_frame1[i, 6]),
            "-",
            "R", rep2, "B", sprintf("%02d", data_frame2[i, 4]), "CRH", sprintf("%02d", data_frame2[i, 6])
          )
          mat.distance.diff[n2*i-n2+j, 2] <- round(dist_func(data_frame1[i, 1:3], data_frame2[j, 1:3]), 2)
        }
      }
    }
    mat.distance.diff = data.frame(mat.distance.diff)%>%
      rename(
        "IDs" = "X1",
        "diff_distances" = "X2"
      )
    mat.distance.diff[, 2] <- as.numeric(mat.distance.diff[, 2])
  }
  
  mat.distance.diff
}


plot_3D_plotly <- function(data_to_plot, color_ref){
  
  data_to_plot <- data_to_plot %>% 
    group_by_(color_ref) %>% 
    mutate(group_id =cur_group_id())%>%
    ungroup()
  
  data_to_plot <- data_to_plot%>%
  left_join(
    data.frame(color = distinctColorPalette(length(unique(data_to_plot$group_id))))%>%
  rownames_to_column("group_id")%>%
    mutate(group_id = as.numeric(group_id)),
  by = "group_id"
  )%>%
    arrange(group_id)%>%
    mutate_(
      group_id = color_ref
    )
  
  fig <- data_to_plot%>%
    plot_ly(
      x = ~X1, 
      y = ~X2, 
      z = ~X3, 
      color = ~group_id, 
      colors = data_to_plot$color
    )
  fig <- fig %>% add_markers()
  fig <- fig %>% layout(
    scene = list(xaxis = list(title = 'X1'),
    yaxis = list(title = 'X2'),
    zaxis = list(title = 'X3'))
  )
  fig
}

## Fonction pour la representation en 3D
plot_3D <- function(data_too_plot, color_ref , display = FALSE, radus = .3, axe_rotate = c(1,0,0), rotate_speed = 3, duration = 10, gif=FALSE){
  
  data_too_plot <- data_too_plot %>% 
    group_by_(color_ref) %>% 
    mutate(group_id =cur_group_id())%>%
    ungroup()
  
  data_too_plot <- data_too_plot%>%
  left_join(
    data.frame(color = distinctColorPalette(length(unique(data_too_plot$group_id))))%>%
  rownames_to_column("group_id")%>%
    mutate(group_id = as.numeric(group_id)),
  by = "group_id"
  )
  
  par3d(windowRect = c(0, 0, 1100, 700))
  plot3d(
    x = as.numeric(unlist(data_too_plot[,1])), 
    y = as.numeric(unlist(data_too_plot[,2])), 
    z = as.numeric(unlist(data_too_plot[,3])), 
    col = data_too_plot$color, 
    type = "s", 
    radius = radus,
    xlab = "X", 
    ylab = "Y", 
    zlab = "Z"
  )
  
  if (display){
    play3d(spin3d(axis = axe_rotate, rpm = rotate_speed), duration = duration) 
  }
  
  if(gif){
    play3d(spin3d(axis = axe_rotate, rpm = rotate_speed), duration = duration)
    movie3d(
      spin3d(axis = axe_rotate, rpm = rotate_speed),
      duration = duration,
      type = "gif",
      dir = ".",
      fps = 20
    )
  }
}

plot_2D <- function(data_too_plot){
  
  g1 <- ggplot(data_too_plot, aes(X1, X2))+
    geom_point()+
    geom_point(aes(colour = factor(replicat)))
  
  g2 <- ggplot(data_too_plot, aes(X1, X3))+
    geom_point()+
    geom_point(aes(colour = factor(replicat)))
  
  g3 <- ggplot(data_too_plot, aes(X2, X3))+
    geom_point()+
    geom_point(aes(colour = factor(replicat)))
  
  ggarrange(g1, g2, g3 + rremove("x.text"), 
          labels = c("A", "B", "C"),
          ncol = 2, nrow = 2)
}

# Fonction pour la creéation de graphs

create_clust_graph <- function(all_data, rep_num, block, min_dist = 3){
  
  par_default <- par(bty = 'n')
  
  three_dim_data <- all_data[all_data$X4==block, 1:3]
  row.names(three_dim_data) <- pull(all_data[all_data$X4==block, 5])
  
  compute_dist <- as.matrix(
    dist(
      x = three_dim_data, 
      method = "euclidean", 
      diag = TRUE
    )
  )
  
  compute_dist_bin <- sapply(
    compute_dist, 
    FUN = function(item) ifelse(item<=min_dist, 1, 0)
  )
  
  compute_dist_bin <- matrix(
    compute_dist_bin, 
    nrow = nrow(compute_dist), 
    ncol = ncol(compute_dist), 
    byrow = TRUE,
    dimnames = list(
      pull(all_data[all_data$X4==block, 5]),
      pull(all_data[all_data$X4==block, 5])
    )
  )

  net <- graph_from_adjacency_matrix(
    compute_dist_bin, 
    mode='undirected'
  )
  net <- simplify(net, remove.multiple = FALSE, remove.loops = TRUE)
  # dev.off()
  par(mar = c(1, 1, 1, 1))
  g <- plot(net, edge.arrow.size=.4,vertex.label=NA, main = paste0("Représenation graphique du block ", block, " pour le replicat ", rep_num))
  g
  par(par_default)
  
  edges <- data.frame(table(unlist(strsplit(attr(E(net)[which_mutual(net)],"vnames"),"\\|"))))%>%
    rename(
      ID = Var1,
      nb_edges = Freq
    )

  # , vertex.color="yellow",vertex.size=15,vertex.label.color="blue",edge.color="red",edge.width=5
  
  res = list(
    #"dist" = compute_dist,
    #"dist_bin" = compute_dist_bin,
    "edges" = edges,
    "plot" = g,
    "net" = net
  )
}

```

```{r message=FALSE, warning=FALSE}
# Importation des données
rep_number = 4

for (j in 1:rep_number) {
  data_url = paste0("https://raw.githubusercontent.com/fmusella/In-silico_Hi-C_GAM_SPRITE/main/data/structures/structure_", j, ".txt")
  data_name = paste("structure_", j, sep="")
  
  assign(
    data_name, 
    read_table(
      data_url, 
      col_names = FALSE
    )
  )
}

# Création d'un identifiant pour chaque lignes
structure_1$ID <- paste0("B", structure_1$X4, sprintf("%03d", 1:nrow(structure_1)))
structure_2$ID <- paste0("B", structure_2$X4, sprintf("%03d", 1:nrow(structure_2)))
structure_3$ID <- paste0("B", structure_3$X4, sprintf("%03d", 1:nrow(structure_3)))
structure_4$ID <- paste0("B", structure_4$X4, sprintf("%03d", 1:nrow(structure_4)))

```

# Représentations graphiques

## Représentation graphique des clusters

```{r}
# 342
structure_1_1_net <- create_clust_graph(structure_1, 1, 1, 3)
structure_1_1_net_comp <- components(structure_1_1_net$net, mode = c("weak", "strong"))
# Il y a 8 qui sont des singletons
structure_1_1 <- data.frame(
    crh_id = structure_1_1_net_comp$membership
  )%>%
  rownames_to_column('ID')%>%
  full_join(structure_1_1_net$edges, by = "ID")%>%
  full_join(structure_1[structure_1$X4==1, ], by = "ID")%>%
  relocate(X1, X2, X3, X4, ID, crh_id, nb_edges)

distance_diff1 <- structure_1_1%>%
  group_by(crh_id) %>%
  summarise(
    m_X1 = round(mean(X1), 2),
    m_X2 = round(mean(X2), 2),
    m_X3 = round(mean(X3), 2),
  )%>%
  relocate(starts_with("m"), crh_id)

structure_2_1_net <- create_clust_graph(structure_2, 2, 1, 3)
structure_2_1_net_comp <- components(structure_2_1_net$net, mode = c("weak", "strong"))
structure_2_1 <- data.frame(
    crh_id = structure_2_1_net_comp$membership
  )%>%
  rownames_to_column('ID')%>%
  full_join(structure_2_1_net$edges, by = "ID")%>%
  full_join(structure_2[structure_2$X4==1, ], by = "ID")%>%
  relocate(X1, X2, X3, X4, ID, crh_id, nb_edges)

distance_diff2 <- structure_2_1%>%
  group_by(crh_id) %>%
  summarise(
    m_X1 = round(mean(X1), 2),
    m_X2 = round(mean(X2), 2),
    m_X3 = round(mean(X3), 2),
  )%>%
  relocate(starts_with("m"), crh_id)

```


## Representation en 3D des CRH en excluant les singletons

```{r, test-rgl, webgl=TRUE}

grp <- plot_3D_plotly(
  structure_1_1%>%
    filter(!is.na(nb_edges))%>%
    mutate(
      rep = "1"
    )%>%
    filter(crh_id %in% 1:4)%>%
  bind_rows(
    structure_2_1%>%
      filter(!is.na(nb_edges))%>%
      mutate(
        rep = "2"
      )%>%
      filter(crh_id %in% 1:4)
  )%>%
    mutate(
      crh_id_ = paste0(rep, crh_id)
    ),
  "crh_id_"
)
grp

n = 4
palette <- distinctColorPalette(n)
pie(rep(1, n), col=palette)

```

# Distance moyenne entre les CRHs

```{r}
dist_r1_r2_bl1 <- m_dist_func(distance_diff1, distance_diff2)

dist_r1_r2_bl1_min <- as.matrix(
  apply(dist_r1_r2_bl1, MARGIN = 1, FUN = min)
)

dist_r1_r2_bl1_min

# dist_r1_r2_bl1%>%
#   mutate(
#     type_echan = substring(dist_echan, 1, 4)
#   )%>%
#   filter(
#     type_echan %in% c("R101", "R102")
#   )%>%
#   ggplot(aes(x=dist_moyen, color=type_echan)) +
#   geom_density()

```



















