---
title: "Construction des CRHs à partir des clusters de cellules obtenus par HicImput"
author: "SAMA Fousseni"
date: "`r Sys.Date()`"
output: word_document
---

```{r message=FALSE, warning=FALSE}
library("devtools")
## Warning: le package 'devtools' a été compilé avec la version R 4.1.3
## Le chargement a nécessité le package : usethis
## Warning: le package 'usethis' a été compilé avec la version R 4.1.3
# Install "HiCImpute" package from github.
# install_github("https://github.com/sl-lin/HiCImpute")
library("HiCImpute")
library("tidyverse")
```

# Présentation des clusters de cellules
```{r message=FALSE, warning=FALSE}
all_paired_structure <- all_paired_structure%>%
    mutate(
      cells_num = str_sub(paire, 2, 4)
    )

load("rdata/cluster_with_imp.rda")
# Présentation des clusters
table(cluster_with_imp$cluster)

```




# Construction des CRHs à partir des clusters de cellules en utilisant les graphs bipartites

```{r message=FALSE, warning=FALSE}
clusters = unique(cluster_with_imp$cluster)
nb_clu = length(clusters)

for (clu in seq_len(nb_clu)) {
  
  class = cluster_with_imp$cluster[cluster_with_imp$cluster==clusters[clu]]
  elems = str_sub(names(class), 5, 7)
  
  # On récupère ici le nombre de réplicat
  clus_stru_data <- all_paired_structure%>%
    filter(cells_num %in% elems)
  paires = unique(clus_stru_data$paire)
  nb_replicas = length(paires)
  init = paires[1]
  # La boucle ira de 1 à 500
  #nb_replicas = 50
  
  for (r in 1:nb_replicas) {
    
    # Initialisation du premier cluster
    if(r==1){
      all_net_result <- create_bip_clust_graph2(
        as_tibble(
          clus_stru_data%>%
            filter(
              paire == init,
              X4 != 1
            )%>%
            select(-c(ends_with("_c"), "paire"))%>%
            mutate(
              ID = paste0("B", sprintf("%02d", X4), sprintf("%04d", 1:n()))
            )
        ),
        promoters_ids, 
        chr, 
        1:16, 
        3,
        sprintf("%03d", cell)
      )
    }else{
      
      structure <- as_tibble(
        clus_stru_data%>%
          filter(paire == str_c(chr, sprintf("%03d", cell)))%>%
          select(-c(ends_with("_c"), "paire"))%>%
          mutate(
            ID = paste0("B", sprintf("%02d", X4), sprintf("%04d", 1:n()))
          )
      )
      
      print("Cluster")
      net <- create_bip_clust_graph2(structure, promoters_ids, chr, 1:16, 3, sprintf("%03d", cell))
      
      print("Overlap")
      overlap_edge <- edge_identity_overlap2(
        net, 
        all_net_result
      )
      
      print("Fusion")
      all_net_result <- fusion_comp2(net, all_net_result, overlap_edge)
      
    }
    
  }
}

```




